# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template-Pluggable
version:      0.13
version_from: lib/HTML/Template/Pluggable.pm
installdirs:  site
requires:
    Class::Trigger:                0
    HTML::Template:                2.7
    Regexp::Common:                0
    Scalar::Util:                  0
    Test::MockObject:              1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
