---
abstract: 'Extends HTML::Template with plugin support'
author:
  - 'Mark Stosberg <mark@summersault.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Template-Pluggable
provides:
  HTML::Template::Pluggable:
    file: lib/HTML/Template/Pluggable.pm
    version: '0.21'
  HTML::Template::Plugin::Dot:
    file: lib/HTML/Template/Plugin/Dot.pm
    version: '1.04'
requires:
  CGI: '3.06'
  Class::Trigger: '0'
  HTML::Template: '2.7'
  Regexp::Common: '0'
  Scalar::Util: '0'
  Test::MockObject: '1'
  Test::More: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
