--- #YAML:1.0
name: HTML-Template-Pluggable
version: 0.15
author:
  - Mark Stosberg <mark@summersault.com>
abstract: Extends HTML::Template with plugin support
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
